config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [:show]

  resources :posts do
    resources :likes, only: [:create, :destroy]
  end
  get 'posts/:post_id/likes' => 'likes#create', as:'posts_likes'
  root 'posts#index'
  resources :aromas


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/aroma.rb
class Aroma < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates_uniqueness_of :post_id, scope: :user_id

end

app/models/post.rb
class Post < ApplicationRecord
 belongs_to :user
 mount_uploader :image, ImageUploader
 has_many :likes, dependent: :destroy
 has_many :liked_users, through: :likes, source: :user
 has_many :post_tag_relations, dependent: :destroy
 has_many :tags, through: :post_tag_relations, dependent: :destroy
 
end

app/models/post_tag_relation.rb
class PostTagRelation < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
    validates :name, presence: true
    has_many :post_tag_relations, dependent: :destroy
    has_many :posts, through: :post_tag_relations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

  validates :name, presence: true
  validates :profile, length: { maximum: 200 }
  
  mount_uploader :image, ImageUploader

 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
    end


end

app/controllers/aromas_controller.rb
class AromasController < ApplicationController
        def index
        end
      
        def new
          @aroma = Aroma.new
        end
      
        def show
          @aroma = Aroma.find_by(id: params[:id])
        end
      
        def create
          @aroma = Aroma.new(aroma_params)
          params[:aroma][:question] ? @aroma.question = params[:aroma][:question].join("") : false
          if @aroma.save
              flash[:notice] = "診断が完了しました"
              redirect_to aroma_path(@aroma.id)
          else
              redirect_to :action => "new"
          end
        end
      
      private
        def aroma_params
            params.require(:aroma).permit(:id, question: [])
        end
end
      
      

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
        like = current_user.likes.create(post_id: params[:post_id]) 
        redirect_back(fallback_location: root_path)
    end
    
    def destroy
        like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]
    def index
        @posts = Post.includes(:liked_users).sort {|a,b| b.liked_users.size <=> a.liked_users.size}
    end    
    
    def new
        @post = Post.new
    end
    
    def create
        post = Post.new(post_params)
        post.user_id = current_user.id
        if post.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
    end
    
    def show
        @post = Post.find(params[:id])
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        post = Post.find(params[:id])
        if post.update(post_params)
          redirect_to :action => "show", :id => post.id
        else
          redirect_to :action => "new"
        end
    end

    def destroy
        post = Post.find(params[:id])
        post.destroy
        redirect_to action: :index
    end

    private
    def post_params
        params.require(:post).permit(:name, :houkoku, :datetime, :goods, :share, :image, tag_ids: [])
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
    end

    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/aromas_helper.rb
module AromasHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/aromas/index.html.erb
<!DOCTYPE html> <!--　この文章がHTML文章であることを伝える要素です。-->
<html lang="ja"><!--言語の指定-->
    <head><!--ページに表示されない情報(サイトの裏側の設定)-->
        <meta charset="utf-8">
        <title>アロマオイル診断スタート</title><!--ブラウザのタブのタイトルを指定-->
    </head>

    <body>
        <header>
            <h1 class="headline">
            <a>Aro_ma</a>
            </h1>
            <ul class="nav-list">
                <li class="nav-list-item">about aroma_oil</li>
                <li class="nav-list-item"><%= link_to "診断", aromas_path, class: "link" %></li>
            </ul>
        </header>

        <div class="start">
            <h6>Are you ready?</h6>
            <%= link_to "診断を始める", new_aroma_path, class: "button" %>
        </div>
    </body>

    <%= link_to "一覧に戻る", posts_path %>

app/views/aromas/new.html.erb
<%= form_for(@aroma, class: 'form-horizontal', role: 'form') do |f| %>
    <div class="container-sindan">
        <div class="row">
            <div class="col-12">
                <p>Question1. どちらかと言うと…</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>じっくり考える方だ</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>考えるより行動する方だ</p>
            </div>

            <div class="col-12">
                <p>Question2. 自分の価値観として近い方は…</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>周りの人と違う存在でありたい</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>周りと同じでいたい</p>
            </div>

            <div class="col-12">
                <p>Question3. 人と接するときは…</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>相手の話をよく聞く方だ</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>自分の話をよくする方だ</p>
            </div>

            <div class="col-12">
                <p>Question4. 大切にしたいのは…</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>論理性だ</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>情緒だ</p>
            </div>
        </div>
    </div>
    <div class="sindanbotan">
        <%= f.submit "post" %>
    </div>
<% end %>

<%= link_to "一覧に戻る", posts_path %>

app/views/aromas/show.html.erb
<div class="intoro">
<h5>診断結果</h5>
<p>あなたにおすすめの香りは…</p>
</div>
<div class="tweet-container">
<div class="tweet">
    <% if @aroma.question == "1111" %>
    <h6>レモン</h6>
    <p>柑橘系の代表的な原料</p>
    <p>清涼感があり、爽やかな印象</p>

    <% elsif @aroma.question == "1112" %>
    <h6>シトラス</h6>
    <p>オレンジに似た柑橘系の果物</p>
    <p>リラックス効果がある</p>

    <% elsif @aroma.question == "1121" %>
    <h6>ローズ</h6>
    <p>華やかで上品な香り</p>
    <p>ストレスを緩和してくれる効果がある</p>

    <% elsif @aroma.question == "1122" %>
    <h6>ラベンダー</h6>
    <p>優しく女性らしい香り</p>
    <p>気持ちを落ち着かせてくれる</p>

    <% elsif @aroma.question == "1211" %>
    <h6>ジャスミン</h6>
    <p>爽やかなのに官能的な香り</p>
    <p>幸福感を得やすい</p>

    <% elsif @aroma.question == "1212" %>
    <h6>ピーチ</h6>
    <p>フレッシュで優しい香り</p>
    <p>アンチエイジングにも最適</p>

    <% elsif @aroma.question == "1221" %>
    <h6>アップル</h6>
    <p>特徴的で甘い香り</p>
    <p>万人受けしやすい</p>

    <% elsif @aroma.question == "1222" %>
    <h6>ユーカリ</h6>
    <p>しっかりとした優しい香り</p>
    <p>浄化作用があり。気持ちを落ち着かせてくれる</p>

    <% elsif @aroma.question == "2111" %>
    <h6>ローズマリー</h6>
    <p>きりりとした強めの香りが特徴的</p>
    <p>美容効果が高い</p>

    <% elsif @aroma.question == "2112" %>
    <h6>ベルガモット</h6>
    <p>柑橘系の果実</p>
    <p>甘くてフレッシュな、万能な香料</p>

    <% elsif @aroma.question == "2121" %>
    <h6>ムスク</h6>
    <p>雄のジャコウジカの腹部にある香嚢から抽出した香料</p>
    <p>官能的で重い香り</p>

    <% elsif @aroma.question == "2122" %>
    <h6>アンバー</h6>
    <p>マッコウクジラの結石から抽出した香料</p>
    <p>魅惑的で色気のある香り</p>

    <% elsif @aroma.question == "2211" %>
    <h6>シナモン</h6>
    <p>甘いスパイスの香り</p>
    <p>香水のアクセントとしてよく使われる</p>

    <% elsif @aroma.question == "2212" %>
    <h6>バニラ</h6>
    <p>甘くて官能的な香り</p>
    <p>上品で年齢を問わず人気が高い</p>

    <% elsif @aroma.question == "2221" %>
    <h6>イランイラン</h6>
    <p>色気のある濃厚で甘い香り</p>
    <p>恋愛に効果があり</p>

    <% elsif @aroma.question == "2222" %>
    <h6>サンダルウッド</h6>
    <p>お香としてよく使われる白檀の香り</p>
    <p>集中力を高める効果もあり</p>

    <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tomato</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
    <script src="https://kit.fontawesome.com/3c4d7f66ab.js"  crossorigin="anonymous"></script> 


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
   <header>
    <h1>おふろんろん</h1>
    <div class="header-list">
     <ul>
      <% if user_signed_in? %>
       <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      <% else %>
       <li><%= link_to "新規登録", new_user_registration_path %></li>
       <li><%= link_to "ログイン", new_user_session_path %></li>
      <% end %>
     </ul>
    </div>
   </header>
   <main>
     <%= yield %>
   </main>

  </body>
</html>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
    <%= f.label :報告 %>
    <%= f.text_field :houkoku, :size => 140 %> 
    <%= f.label :使用したお風呂グッズ %>
    <%= f.text_field :goods, :size => 140 %> 
    <%= f.label :画像 %>
    <%= f.file_field :image %>

    <%= f.label :share %>
    <%= f.text_field :share, :size => 140 %> 
    
    
    <%= f.submit "編集する" %>

    <%= link_to "一覧に戻る", posts_path %>

<% end %>

app/views/posts/index.html.erb
<h1>お風呂って楽しいよね！？^_^</h1>
<h3>一覧ページ</h3>
<%= link_to "新規投稿へ", new_post_path %>
<%= link_to "アロマオイル診断", aromas_path %>
<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>
<div class="posts-container">
  <% @posts.each do |t| %>
    <div class="post">
      <%= image_tag t.user.image_url, size: "250x200" if t.user.image? %>
      <%= image_tag t.image_url, size: "250x200" if t.image? %>
      <%= link_to t.user.name, user_path(t.user.id) %>
      <%= t.houkoku %>
      <%= t.datetime %>
      <%= t.goods %>
      <%= t.share %>

    <% if user_signed_in? %>
        <% if current_user.already_liked?(t) %>
            <%= button_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
                <i class="fas fa-heart"></i><%= t.likes.count %>
            <% end %>
        <% else %>
            <%= button_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
                <i class="far fa-heart"></i><%= t.likes.count %>
            <% end %>
        <% end %>
      <% else %>
        <i class="far fa-heart"></i><%= t.likes.count %>
    <% end %>

      <div class="right-container">
        <%= link_to "詳細へ", post_path(t.id) %>
        <%= link_to "編集する", edit_post_path(t.id) %>
        <%= button_to "削除する", post_path(t.id), method: :delete %>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>tomatooto</h1>
<h3>新規投稿ページ</h3>
<%= form_for @post do |f| %>

  <div class="field">
    <%= f.label :報告  %>
    <%= f.select :houkoku, 
    [["お風呂がんばるよ！", "お風呂がんばるよ！"], 
    ["お風呂入ったよ！", "お風呂入ったよ！"]], include_blank: "選択して下さい" %>
  </div>

  <div class="field">
   <%= f.label :お風呂グッズ %>
   <%= f.text_field :goods, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :share  %>
    <%= f.text_area :share, :size => "30x2" %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>  

  <div class='form-group'>
    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
      <div class='form-check'>
          <%= tag.label class: 'form-check-label' do %>
              <%= tag.check_box class: 'form-check-input' %>
              <%= tag.text %>
          <% end %>
      </div>
    <% end %>
  </div>

  <%= f.submit "お風呂状況をみんなに知らせる！！" %>
<% end %>

<%= link_to "一覧に戻る", posts_path %>

app/views/posts/show.html.erb
<h1>tomatooto</h1>
<h3>投稿の詳細</h3>


<div class="post">
    <p><%= @post.houkoku %></p>
    <p><%= @post.datetime %></p>
    <p><%= @post.goods %></p>
    <%= image_tag @post.image_url, size: "250x200" if @post.image? %>
    <p><%= @post.share %></p>
    <p><%= @post.created_at %></p>

    <% @post.tags.each do |tag| %>
      <span><%= tag.name %></span>
    <% end %>

    <% if user_signed_in? %>
      <% if current_user.already_liked?(@post) %>
        <%= button_to post_like_path(@post), method: :delete do %>
            <i class="fas fa-heart"></i><%= @post.likes.count %>
        <% end %>
      <% else %>
        <%= button_to post_likes_path(@post), method: :post do %>
            <i class="far fa-heart"></i><%= @post.likes.count %>
        <% end %>
      <% end %>
    <% else %>
        <i class="far fa-heart"></i><%= @post.likes.count %>
    <% end %>

</div>

<h2>いいねしたユーザー</h2>
<% @post.liked_users.each do |user| %>
  <li><%= user.name %></li>
<% end %>

<%= link_to "編集する", edit_post_path(@post.id) %>
<%= link_to "Post一覧に戻る", posts_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>マイページ</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<%= image_tag @user.image_url, size: "250x200" if @user.image? %>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>わたしの投稿一覧</h2>
<% @user.posts.each do |t| %>
  <%= t.user.name %>
  <%= t.houkoku %>
  <%= t.datetime %>
  <%= t.goods %>
  <%= t.share %>
<% end %>


<%= link_to "Post一覧に戻る", posts_path %>